# cluster_config.yml - cluster configuration
__default__:
    account: ctbrowngrp
    partition: low2
    #mail-type: FAIL,TIME_LIMIT
    #mail-user: ntpierce@ucdavis.edu
    #nodes: 1
    #ntasks-per-node: 1
    #job-name: "{rule}.w{wildcards}"
    #job-name: "{rule}"
    #chdir: "/home/ntpierce/2020-gtdb-smash"
    logdir: "/home/ntpierce/2020-gtdb-smash/slurm-logs/"
    #error: "slurm-%j.stderr"
    #output: "slurm-%j.stdout"

#index_lca:
#    partition: bmh
