

#out_dir: gtdb-indices
out_dir: index-gtdb
sigs_dir: index-gtdb/sigs

representative_indices:
#  gtdb_pep.rep_family:
#    input_type: protein
#    input_path: /home/ntpierce/2020-gtdb-smash/gtdb_r89_rep_genomes_faa
#    info_csv: /home/ntpierce/2020-gtdb-smash/gtdb-lineages.protein-filenames.n0th-representative-at-family.csv
#    gather_csv: /home/ntpierce/2020-gtdb-smash/gtdb-lineages.protein-filenames.n1th-representative-at-family.csv
#    index_outdir: "index-gtdb"
#    index_types:
#        - lca
#    alphabet:
#      protein:
#        ksizes: [11] #[7,9,11] #[7,9,11]
#        scaled: [100]
#      dayhoff:
#        ksizes: [19] #[17,19,21,23,25]
#        scaled: [100]
#      hp:
#        ksizes: [35] #[31,33,35]
#        scaled: [100]
#  gtdb_pep.rep_order:
#    input_type: protein
#    input_path: /home/ntpierce/2020-gtdb-smash/gtdb_r89_rep_genomes_faa
#    info_csv: /home/ntpierce/2020-gtdb-smash/gtdb-lineages.protein-filenames.n0th-representative-at-order.csv
#    gather_csv: /home/ntpierce/2020-gtdb-smash/gtdb-lineages.protein-filenames.n1th-representative-at-order.csv
#    index_outdir: "index-gtdb"
#    index_types:
#        - lca
#        #- sbt
#    alphabet:
#      protein:
#        ksizes: [7,9,11,13] #[5,7,9,11,13,15] #[7,9,11] 
#        scaled: [100]
#      dayhoff:
#        ksizes: [15,17,19,21] #,23,25] #[17,19,21,23,25] 
#        scaled: [100] #100
#      hp:
#        ksizes: [31,33,35] #[29,31,33,35,37] #[31,33,35]
#        scaled: [100]

  #gtdb_rna.rep_order:
  #  input_type: rna
  #  input_path: /home/ntpierce/2020-gtdb-smash/gtdb_r89_rep_genomes_rna_fna
  #  info_csv: /home/ntpierce/2020-gtdb-smash/gtdb-lineages.rna-filenames.n0th-representative-at-order.csv
  #  gather_csv: /home/ntpierce/2020-gtdb-smash/gtdb-lineages.rna-filenames.n1th-representative-at-order.csv
  #  index_outdir: "index-gtdb"
  #  index_types:
  #      - lca
  #      #- sbt
  #  alphabet:
  #    nucleotide:
  #      ksizes: [31] #[21,31,51] 
  #      scaled: [1000]
  gtdb_rna.rep_genus:
    input_type: rna
    input_path: /home/ntpierce/2020-gtdb-smash/gtdb_r89_rep_genomes_rna_fna
#    info_csv: /home/ntpierce/2020-gtdb-smash/gtdb-lineages.rna-filenames.n0th-representative-at-genus.csv
    info_csv: /home/ntpierce/2020-gtdb-smash/gtdb-lineages.rna-filenames.n1th-representative-at-genus.csv
    index_outdir: "index-gtdb"
    index_types:
        - lca
        #- sbt
    alphabet:
      nucleotide:
        ksizes: [21,31,51] 
        scaled: [1000]
      translate_protein:
        ksizes: [11] #[5,6,7,9,11,13] #5,7
        scaled: [100] #[50, 200, 1000] # 1
      translate_dayhoff:
        ksizes: [19] #[5,6,7,8,9,11,12,13,15,17] #11,13
        scaled: [100] #[50, 200, 1000] #1
      translate_hp:
        ksizes: [35] #[15,16,17,18,19,21,23,25] #[15,17,19,21]
        scaled: [100] #[50, 200, 1000]

#  gtdb_pep.rep_genus:
#    input_type: protein
#    input_path: /home/ntpierce/2020-gtdb-smash/gtdb_r89_rep_genomes_faa
#    info_csv: /home/ntpierce/2020-gtdb-smash/gtdb-lineages.protein-filenames.n0th-representative-at-genus.csv
#    gather_csv: /home/ntpierce/2020-gtdb-smash/gtdb-lineages.protein-filenames.n1th-representative-at-genus.csv
#    index_outdir: "index-gtdb"
#    index_types:
#        - lca
#    alphabet:
      #protein:
      #  ksizes: [11] #[7,9,11]
      #  scaled: [100]
     #dayhoff:
     #  ksizes: [19] #[17,19,21,23,25]
      #  scaled: [100]
#      hp:
#        ksizes: [33] #[31,33,35]
#        scaled: [100]

# grow full evol paths sbt:
#  evol_paths_pep.rep_family:
#      input_type: protein
      #query_csv: /home/ntpierce/2020-gtdb-smash/gtdb_evol_groups.correct-lineages.with_filenames.representative-at-family.csv
#      build_index:
#        input_path: /home/ntpierce/2020-gtdb-smash/gtdb_r89_rep_genomes_faa
        # if lca, this must have lineage info in it
#        info_csv: /home/ntpierce/2020-gtdb-smash/gtdb_evol_groups.correct-lineages.with_filenames.representative-at-family.csv
#        index_outdir: "evol_distances/sbts"
#        index_types:
#          - lca
#      alphabet:
#        protein:
#          ksizes: [7] #[5,7,9,11,13]
#          scaled: [10] # [200]
#        dayhoff:
#          ksizes: [19] #[11,13,15,17,19,21,23,25,27] #,21] #[19,21,23,25,27] #[13,15,17,19,21,23,25]  #[19, 21, 23] #[13,15,19,17,21,23,25] #19
#          scaled: [10] #[200]
#        hp:
#          ksizes: [33] #[23,25,27,29,31,33,41] #27,29,31,33] #[23,25,27,29,31,33] #[25, 27] #[23,25,27,29,31,33]
#          scaled: [10] #[200]

#  evol_paths_pep.rep_order:
#    input_type: protein
#    input_path: /home/ntpierce/2020-gtdb-smash/gtdb_r89_rep_genomes_faa
    # if lca, this must have lineage info in it
#    info_csv: /home/ntpierce/2020-gtdb-smash/gtdb_evol_groups.correct-lineages.with_filenames.representative-at-order.csv
#    index_outdir: "evol_distances/sbts"
#    index_types:
#      - lca
#    alphabet:
#      protein:
#        ksizes: [7,9,11,13] #[5,7,9,11,13]
#        scaled: [10] # [200]
#      dayhoff:
#        ksizes: [17,19,21,23,25] #[11,13,15,17,19,21,23,25,27] #,21] #[19,21,23,25,27] #[13,15,17,19,21,23,25]  #[19, 21, 23] #[13,15,19,17,21,23,25] #19
#        scaled: [10] #[200]
#      hp:
#        ksizes: [29,31,33] #[23,25,27,29,31,33,41] #27,29,31,33] #[23,25,27,29,31,33] #[25, 27] #[23,25,27,29,31,33]
#        scaled: [10] #[200] 
 
  #evol_paths_rna:
  #  input_type: rna
  #  query_csv: /home/ntpierce/2020-gtdb-smash/gtdb_evol_groups.with_rna_filenames.csv
    #use_existing_sbt: ""  # alternatively: use a prebuilt sbt, don't generate new one 
  #  grow_sbt:
  #    input_path: /home/ntpierce/2020-gtdb-smash/gtdb_r89_rep_genomes_rna_fna 
  #    subset_csv: /home/ntpierce/2020-gtdb-smash/gtdb_evol_groups.with_rna_filenames.csv
  #    sbt_outdir: "evol_distances/sbts"
  #  alphabet:
  #    nucleotide:
  #      ksizes: [21,31,51]
  #      scaled: [1000]  #[50,200,1000,2000]
#      translate_protein:
#        ksizes: [5,6,7,9,11,13] #5,7
#        scaled: [50, 200, 1000] # 1
#      translate_dayhoff:
#        ksizes: [5,6,7,8,9,11,12,13,15,17] #11,13
#        scaled: [50, 200, 1000] #1
#      translate_hp:
#        ksizes: [15,16,17,18,19,21,23,25] #[15,17,19,21]
#        scaled: [50, 200, 1000]
#  evol_paths_dna:
#    input_type: dna
#    query_csv: /home/ntpierce/2020-gtdb-smash/gtdb_evol_groups.with_dna_filenames.csv
#    #use_existing_sbt: ""  # alternatively: use a prebuilt sbt, don't generate new one 
#    grow_sbt:
#      input_path: /home/ctbrown/gtdbtk/release89/fastani/database 
#      subset_csv: /home/ntpierce/2020-gtdb-smash/gtdb_evol_groups_.with_dna_filenames.csv
#      sbt_outdir: "evol_distances/sbts"
#    alphabet:
#      nucleotide:
#        ksizes: [21,31] #,51]
#        scaled: [1000] #[50,200,1000,2000]
#      translate_protein:
#        ksizes: [5,6,7,9,11,13] #5,7
#        scaled: [50, 200, 1000]
#      translate_dayhoff:
#        ksizes: [5,6,7,8,9,11,12,13,15,17] #11,13
#        scaled: [50, 200, 1000]
#      translate_hp:
#        ksizes: [15,16,17,18,19,21,23,25] #[15,17,19,21]
#        scaled: [50, 200, 1000] # 1 is taking forever
