

#out_dir: gtdb-indices
out_dir: index-gtdb
sigs_dir: index-gtdb/sigs
index_dir: index-gtdb

samples:
  #gtdb_rna:
    #input_type: rna
    #input_path: /home/ntpierce/2020-gtdb-smash/gtdb_r89_rep_genomes_rna_fna
    #info_csv: /home/ntpierce/2020-gtdb-smash/gtdb-lineages.rna-filenames.with-signames.csv
    #info_csv: /home/ntpierce/2020-gtdb-smash/gtdb_evol_groups.with_rna_filenames.csv
    #info_csv: /home/ntpierce/2020-gtdb-smash/gtdb_evol_groups.with_rna_filenames.with-signames.csv
    #alphabet:
      #purine-pyrimidine:
      #  ksizes: [41,51] #,21,31]
      #  scaled: [1000]
      #weak-strong:
      #  ksizes: [31,41] # [21,51]
      #  scaled: [1000]
      #amino-keto:
      #  ksizes: [31,41] # [21,51]
      #  scaled: [1000]
      #skipmer_nucleotide:
        #ksizes: [17,21,31,51]
        #scaled: [1000]  
#  gtdb_dna:
#    input_type: dna
#    input_path: /home/ctbrown/gtdbtk/release89/fastani/database 
    #info_csv: /home/ntpierce/2020-gtdb-smash/gtdb-lineages.dna-filenames.n0th-representative-at-genus.csv
#    info_csv: /home/ntpierce/2020-gtdb-smash/gtdb-lineages.dna-filenames.csv
#    alphabet:
#      nucleotide:
#        ksizes: [21,31,51] 
#        scaled: [1000]
#      translate_protein:
#        ksizes: [11] 
#        scaled: [100]
#      translate_dayhoff:
#        ksizes: [19]
#        scaled: [100]
#      translate_hp:
#        ksizes: [35]
#        scaled: [100]
  gtdb_pep:
    input_type: protein
    input_path: /home/ntpierce/2020-gtdb-smash/gtdb_r89_rep_genomes_faa
    #info_csv: /home/ntpierce/2020-gtdb-smash/gtdb-lineages.protein-filenames.with-signames.csv
    info_csv: /home/ntpierce/2020-gtdb-smash/gtdb_evol_groups.with_filenames.with-signames.csv
    alphabet:
      bs62:
        ksizes: [11,13,15,17,19,21] #[7,9,11]
        scaled: [100]
      #aa9:
      #  ksizes: [11,13,15,17,19,21] #[7,9,11]
      #  scaled: [100]
      #gbmr4:
      #  ksizes: [17,19,21,23,25,27,29,31] #[7,9,11]
      #  scaled: [100]
      #sdm12:
      #  ksizes: [11,13,15,17,19,21] #[7,9,11]
      #  scaled: [100]
      #hsdm17:
      #  ksizes: [5,7,9,11,13,15,17,19,21] #[7,9,11]
      #  scaled: [100]
      #botvinnik8:
      #  ksizes: [11,13,15,17,19,21] #[7,9,11]
      #  scaled: [100]
