
output_dir: gtdb_pepsmash

# lineages to explore
lineage_csv: gtdb-lineages.csv
genome_lineage_list: genome-lineage-list.txt
# local gtdb database
gtdb_datadir: /home/ctbrown/gtdbtk/release89/fastani/database/
gtdb_protein_datadir: "gtdb_r89_rep_genomes_faa"
protein_input: True
translate: True
sourmash_params:
  encoding:
    dna:
      ksize:
        - 21
        - 31
        - 51
      scaled:
        - 2000
        - 1000
        - 200
        - 1
    rna:
      ksize:
        - 21
        - 31
        - 51
      scaled:
        - 2000
        - 1000
        - 200
        - 1
    protein:
      ksize:
        - 5
        - 7
        - 9
        - 11
      scaled:
        - 1000
        - 200
        - 1
    dayhoff:
      ksize:
        - 9
        - 11
        - 13
        - 15
      scaled:
        - 500
        - 200
        - 1
    hp:
      ksize:
        - 15
        - 17
        - 19
        - 21
      scaled:
        - 500
        - 200
        - 1
