
output_dir: gtdb_pepsmash

# lineages to explore
lineage_csv: gtdb-lineages.csv
#samples_csv: gtdb_evol_groups.tsv
samples_csv: gtdb_evol_groups_first_three.tsv 
# local gtdb database
gtdb_datadir: /home/ctbrown/gtdbtk/release89/fastani/database/
gtdb_protein_datadir: "gtdb_r89_rep_genomes_faa"
gtdb_rna_datadir: "gtdb_r89_rep_genomes_protein_fna"
protein_input: True
genome_sigs: True
rna_sigs: True
translate: True
sourmash_params:
  encoding:
    dna:
      ksize:  [31] #[21,31,51]
      scaled: [2000] #[2000, 1000, 500]
    rna:
      ksize: [31] #[21,31,51]
      scaled: [2000] #[2000, 1000, 500] 
    protein:
      ksize: [7] #[5,7,9,11]
      scaled: [1] #200?
    dayhoff: 
      ksize: [13] # [9,11,13,15] 
      scaled: [1] #200?
    hp:
      ksize:  [17] #[15,17,19,21]
      scaled: [1] #200?
