# cluster_config.yml - cluster configuration
__default__:
    account: ctbrowngrp
    partition: low2
    #mem: 5000
    mail-type: FAIL,TIME_LIMIT
    #mail-user: ntpierce@ucdavis.edu
    nodes: 1
    ntasks-per-node: 1
    job-name: "{rule}.w{wildcards}"
    chdir: "/home/ntpierce/2020-gtdb-smash"
    logdir: "/home/ntpierce/2020-gtdb-smash/gtdb_sbts/slurm-logs/"
    #stderr: "slurm-%j.stderr"
    #stdout: "slurm-%j.stdout"

index_lca:
    account: ctbrowngrp
    partition: bmm
    mail-type: FAIL,TIME_LIMIT
    #mail-user: ntpierce@ucdavis.edu
    nodes: 1
    ntasks-per-node: 1
    job-name: "{rule}.w{wildcards}"
    chdir: "/home/ntpierce/2020-gtdb-smash"
    logdir: "/home/ntpierce/2020-gtdb-smash/gtdb_sbts/slurm-logs/"
    #stderr: "slurm-%j.stderr"
    #stdout: "slurm-%j.stdout"

lca_to_sbt:
    account: ctbrowngrp
    partition: bmm
    mail-type: FAIL,TIME_LIMIT
    #mail-user: ntpierce@ucdavis.edu
    nodes: 1
    ntasks-per-node: 1
    job-name: "{rule}.w{wildcards}"
    chdir: "/home/ntpierce/2020-gtdb-smash"
    logdir: "/home/ntpierce/2020-gtdb-smash/gtdb_sbts/slurm-logs/"
    #stderr: "slurm-%j.stderr"
    #stdout: "slurm-%j.stdout"
